stages:
  - build
  - deploy

include:
  - project: 'CROC.DRPO_RnD/jxfw/sandbox/school2024/corpbot/environment'
    ref: main
    file: 'deploy.yml'

.build:
  stage: build
  image: "openjdk:21"
  cache:
    key: ${CI_PROJECT_NAME}
    paths:
      - $MAVEN_REPO_LOCAL

build:
  extends: .build
  script:
    - ./mvnw spring-boot:build-image -D'spring-boot.build-image.imageName=localhost:32000/${project.artifactId}:${project.version}' -Dspring-boot.build-image.publish=true
  only:
    refs:
      - empty

build_mr:
  extends: .build
  script:
    - ./mvnw install
  artifacts:
    when: always
    paths:
      - target/*.jar
  only:
    - merge_requests