apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee
  labels:
    app.kubernetes.io/name: employee
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: employee
  template:
    metadata:
      labels:
        app.kubernetes.io/name: employee
    spec:
      restartPolicy: Always
      containers:
        - name: service
          image: localhost:32000/employee:latest
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
              path: actuator/health/readiness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 30
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: actuator/health/liveness
              port: 8080
            periodSeconds: 10
            failureThreshold: 60
          resources:
            limits:
              cpu: "1"
              memory: 800Mi
            requests:
              cpu: 250m
              memory: 800Mi
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-0.postgres.default:5432/employee"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "passwordswordpassword"
---
apiVersion: v1
kind: Service
metadata:
  name: employee
  labels:
    app.kubernetes.io/name: employee
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: employee